steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/nextjs-app:$COMMIT_SHA', '.']

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/nextjs-app:$COMMIT_SHA']

  # Step 3: Deploy the Docker image to Google Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'nextjs-app',
      '--image', 'gcr.io/$PROJECT_ID/nextjs-app:$COMMIT_SHA',
      '--platform', 'managed',
      '--region', 'us-central1',
      '--allow-unauthenticated'
    ]

# Set the service account and region for Cloud Build
images:
  - 'gcr.io/$PROJECT_ID/nextjs-app:$COMMIT_SHA'

timeout: '900s'
options:
  logging: CLOUD_LOGGING_ONLY

# Specify the service account
serviceAccount: 'cloud-build-sa@my-website-445708.iam.gserviceaccount.com'
